apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybookdb
  labels:
    app: mybookdb
spec:
  selector: 
    matchLabels:
      app: mybookdb
  replicas: 1
  template:
    metadata:
      labels:
        app: mybookdb
      name: mybookdb
    spec:
      containers:
      - image: mongo:latest
        name: mybookdb 
        ports:
        - containerPort: 27017
                       
       